### ISSUE TITLE
how to use this project for android?

### ISSUE THREAD

**Issue by zhjunliu** [lichao890427/DataRecovery#1]
how to use this project for android?

**Comment by lich4** [comment]
This is my early work that I started learning programming around 2012, only for display without maintenance
This is a project for Windows

**Comment by lich4** [comment]
> how to use this project for android?

This is my early work that I started learning programming around 2012, only for display without maintenance
This is a project for Windows

**Comment by lich4** [comment]
> how to use this project for android?


This is my early work that I started learning programming around 2012, only for display without maintenance, a windows project
