### ISSUE TITLE
属性列表情况以及MFT碎片无法处理

### ISSUE THREAD

**Issue by sszth** [lichao890427/DataRecovery#2]
没有考虑当属性在20H中的情况 以及MFT碎片，  如1G的NTFS分区   如果某级目录下有30w个1kb文件  依照目前代码无法列举出

**Comment by lich4** [comment]
这是我2012年左右刚自学编程的作品了，难免有疏漏，那时候连数据结构算法是啥还不知道。仅做展示，不维护了
